#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/ibsardar/363/MPC-master/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: Proj3

depend: Proj3-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Proj3 $(@)

.PHONY: Proj3
Proj3:
	@$(MAKE) -f Makefile.Proj3 all

.PHONY: Proj3-depend
Proj3-depend:
	@$(MAKE) -f Makefile.Proj3 depend

project_name_list:
	@echo Proj3
